const config = {
  bitsharesNodes: {
    list: {
      'wss://bitshares.openledger.info/ws': { location: 'Nuremberg, Germany' },
      'wss://eu.openledger.info/ws': { location: 'Berlin, Germany' },
      // 'wss://bit.btsabc.org/ws': { location: 'Hong Kong' },
      'wss://bts.ai.la/ws': { location: 'Hong Kong' },
      'wss://bitshares.apasia.tech/ws': { location: 'Bangkok, Thailand' },
      'wss://japan.bitshares.apasia.tech/ws': { location: 'Tokyo, Japan' },
      // 'wss://bitshares.dacplay.org/ws': { location: 'Hangzhou, China' },
      'wss://bitshares-api.wancloud.io/ws': { location: 'China' },
      // 'wss://openledger.hk/ws': { location: 'Hong Kong' },
      'wss://bitshares.crypto.fans/ws': { location: 'Munich, Germany' },
      'wss://ws.gdex.top': { location: 'China' },
      'wss://dex.rnglab.org': { location: 'Netherlands' },
      'wss://dexnode.net/ws': { location: 'Dallas, USA' },
      'wss://kc-us-dex.xeldal.com/ws': { location: 'Kansas City, USA' },
      'wss://btsza.co.za:8091/ws': { location: 'Cape Town, South Africa' },
      'wss://api.bts.blckchnd.com': { location: 'Falkenstein, Germany' },
      'wss://api-ru.bts.blckchnd.com': { location: 'Moscow, Russia' },
      'wss://eu.nodes.bitshares.ws': {
        location: 'Central Europe - BitShares Infrastructure Program'
      },
      'wss://us.nodes.bitshares.ws': {
        location: 'U.S. West Coast - BitShares Infrastructure Program'
      },
      'wss://sg.nodes.bitshares.ws': { location: 'Singapore - BitShares Infrastructure Program' },
      'wss://ws.winex.pro': { location: 'Singapore' }
    },
    defaultNode: 'wss://bitshares.openledger.info/ws'
  },
  defaultAssetsNames: ['USD', 'OPEN.BTC', 'OPEN.ETH', 'OPEN.DASH', 'OPEN.LTC',
    'OPEN.EOS', 'OPEN.STEEM', 'BTS', 'TRUSTY', 'TWENTIX', 'NOWCOIN'],
  referrer: 'trfnd',
  removePrefix: 'OPEN.',
  faucetUrl: 'https://faucet.trusty.fund/signup',
  marketBases: ["BTC", "ETH", "BTS", "USD", "CNY"],
  defaultMarkets: { 'BTC': [
    "BTS",
    "OPEN.ETH",
    "OPEN.DASH",
    "BLOCKPAY",
    "OPEN.DGD",
    "OPEN.STEEM",
    "OPEN.USDT",
    "OPEN.MAID",
  ], 'ETH': [
    "BTS",
    "OPEN.BTC",
    "OPEN.DASH",
    "BLOCKPAY",
    "OPEN.DGD",
    "OPEN.STEEM",
    "OPEN.USDT",
    "OPEN.MAID",
  ], 'BTS': [
    "OPEN.ETH",
    "OPEN.EOS",
    "PPY",
    "OPEN.STEEM",
    "OBITS",
    "RUBLE",
    "HERO",
    "OCT",
    "SILVER",
    "GOLD",
    "BLOCKPAY",
    "BTWTY",
    "SMOKE",
    "GDEX.BTC",
    "GDEX.ETH",
    "GDEX.EOS",
    "GDEX.BTO",
    "OPEN.EOSDAC",
    "OPEN.MAID",
    "OPEN.HEAT",
    "OPEN.INCENT",
    "RUDEX.MUSE",
    "RUDEX.TT",
    "RUDEX.SCR",
    "RUDEX.ETH",
    "RUDEX.DGB",
    "XBTSX.STH",
    "ZEPH",
    "HERTZ",
    "SPARKDEX.BTC",
    "SPARKDEX.ETH",
    "RUDEX.SBD",
    "RUDEX.KRM",
    "RUDEX.STEEM"
  ], 'USD': [
    "BTS",
    "OPEN.BTC",
    "OPEN.USDT",
    "OPEN.ETH",
    "OPEN.DASH",
    "OPEN.STEEM",
    "OPEN.MAID",
    "GOLD",
    "HERO",
    "GDEX.BTC",
    "GDEX.ETH",
    "GDEX.EOS",
    "GDEX.BTO",
    "OPEN.EOSDAC",
    "RUDEX.STEEM",
    "RUDEX.KRM"
  ], 'CNY': [
    "BTS",
    "OPEN.BTC",
    "USD",
    "OPEN.ETH",
    "YOYOW",
    "OCT",
    "GDEX.BTC",
    "GDEX.ETH",
    "GDEX.EOS",
    "GDEX.BTO",
    "GDEX.BTM",
    "RUDEX.GOLOS",
    "RUDEX.GBG"
  ]},
  
};

export default config;
