export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';
export const WS_ERROR = 'WS_ERROR';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_COMPLETE = 'FETCH_USER_COMPLETE';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const WALLET_CREATED = 'WALLET_CREATED';
export const WALLET_BRAINKEY_BACKUP = 'WALLET_BRAINKEY_BACKUP';
export const WALLET_LOCK = 'WALLET_LOCK';
export const WALLET_UNLOCK = 'WALLET_UNLOCK';

export const FETCH_ASSETS_REQUEST = 'FETCH_ASSETS_REQUEST';
export const FETCH_ASSETS_COMPLETE = 'FETCH_ASSETS_COMPLETE';
export const FETCH_ASSETS_ERROR = 'FETCH_ASSETS_ERROR';
export const FETCH_DEFAULT_ASSETS_REQUEST = 'FETCH_DEFAULT_ASSETS_REQUEST';
export const FETCH_DEFAULT_ASSETS_COMPLETE = 'FETCH_DEFAULT_ASSETS_COMPLETE';
export const FETCH_DEFAULT_ASSETS_ERROR = 'FETCH_DEFAULT_ASSETS_ERROR';

export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';
export const ACCOUNT_CREATE_ERROR = 'ACCOUNT_CREATE_ERROR';
export const ACCOUNT_FETCHED = 'ACCOUNT_FETCHED';
