export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';
export const RPC_STATUS_UPDATE = 'RPC_STATUS_UPDATE';


export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_COMPLETE = 'FETCH_USER_COMPLETE';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const WALLET_SIGNUP_REQUEST = 'WALLET_SIGNUP_REQUEST';
export const WALLET_SIGNUP_COMPLETE = 'WALLET_SIGNUP_COMPLETE';
export const WALLET_SIGNUP_ERROR = 'WALLET_SIGNUP_ERROR';
export const WALLET_LOGIN_REQUEST = 'WALLET_LOGIN_REQUEST';
export const WALLET_LOGIN_COMPLETE = 'WALLET_LOGIN_COMPLETE';
export const WALLET_LOGIN_ERROR = 'WALLET_LOGIN_ERROR';
export const WALLET_LOCK = 'WALLET_LOCK';
export const WALLET_UNLOCK = 'WALLET_UNLOCK';
export const WALLET_BRAINKEY_BACKUP = 'WALLET_BRAINKEY_BACKUP';
export const SET_WALLET_USER_DATA = 'SET_WALLET_USER_DATA';

export const FETCH_ASSETS_REQUEST = 'FETCH_ASSETS_REQUEST';
export const FETCH_ASSETS_COMPLETE = 'FETCH_ASSETS_COMPLETE';
export const FETCH_ASSETS_ERROR = 'FETCH_ASSETS_ERROR';
export const FETCH_DEFAULT_ASSETS_REQUEST = 'FETCH_DEFAULT_ASSETS_REQUEST';
export const FETCH_DEFAULT_ASSETS_COMPLETE = 'FETCH_DEFAULT_ASSETS_COMPLETE';
export const FETCH_DEFAULT_ASSETS_ERROR = 'FETCH_DEFAULT_ASSETS_ERROR';

export const SAVE_DEFAULT_ASSETS_IDS = 'SAVE_DEFAULT_ASSETS_IDS';

export const FETCH_PORTFOLIO_ASSET_REQUEST = 'FETCH_PORTFOLIO_ASSET_REQUEST';
export const FETCH_PORTFOLIO_ASSET_ERROR = 'FETCH_PORTFOLIO_ASSET_ERROR';
export const FETCH_PORTFOLIO_ASSET_COMPLETE = 'FETCH_PORTFOLIO_ASSET_COMPLETE';
export const RESET_PORTFOLIO_STATE = 'RESET_PORTFOLIO_STATE';
